services:
  - name: tire-unblocker
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: "3000"
    healthCheckPath: /
    automaticDeploy:
      branchPattern: main
